In [1]:
import numpy as np
import random

QUESTION: Working with GPA

a

In [36]:
# Generate GPAs for 20 students between 2.0 and 4.0
np.random.seed(42)  # Ensuring the same random values every time
gpas = np.random.uniform(2.0, 4.0, 20)
print("GPAs:", gpas)


GPAs: [2.74908024 3.90142861 3.46398788 3.19731697 2.31203728 2.31198904
 2.11616722 3.73235229 3.20223002 3.41614516 2.04116899 3.9398197
 3.66488528 2.42467822 2.36364993 2.36680902 2.60848449 3.04951286
 2.86389004 2.58245828]


b

In [41]:
# Find the highest two and lowest two GPAs
gpas_sorted = np.sort(gpas)
highest_two = gpas_sorted[-2:]
lowest_two = gpas_sorted[:2]
print("Highest Two GPAs:", highest_two)
print("----------------------------------------------------------")
print("Lowest Two GPAs:", lowest_two)

Highest Two GPAs: [3.90142861 3.9398197 ]
----------------------------------------------------------
Lowest Two GPAs: [2.04116899 2.11616722]


c

In [42]:
# Remove the highest and lowest GPAs, then compute new average
gpas_trimmed = gpas_sorted[2:-2]
print("Updated GPAs after dropping highest and lowest:", gpas_trimmed)
print("--------------------------------------------------------------------")
print("New Average GPA:", np.mean(gpas_trimmed))


Updated GPAs after dropping highest and lowest: [2.31198904 2.31203728 2.36364993 2.36680902 2.42467822 2.58245828
 2.60848449 2.74908024 2.86389004 3.04951286 3.19731697 3.20223002
 3.41614516 3.46398788 3.66488528 3.73235229]
--------------------------------------------------------------------
New Average GPA: 2.8943441878649745


d

In [45]:
# Switch first and second half of an array
test_arr = np.arange(10)
mid = len(test_arr) // 2
switched_arr = np.concatenate((test_arr[mid:], test_arr[:mid]))
print("Original Array:", test_arr)
print("----------------------------------------------------------")
print("Switched Array:", switched_arr)


Original Array: [0 1 2 3 4 5 6 7 8 9]
----------------------------------------------------------
Switched Array: [5 6 7 8 9 0 1 2 3 4]


QUESTION 2: Working with Matrices

a

In [50]:
# Create 5x5 random integer array and replace 3rd column with 1
array_5x5 = np.random.randint(1, 21, (5, 5))
array_5x5[:, 2] = 1  # Setting the entire third column to 1
print("5x5 array with 1 in the third column:")
print(array_5x5)

5x5 array with 1 in the third column:
[[ 7 17  1  4  5]
 [ 7 13  1 11  4]
 [13  7  1  2 10]
 [13  6  1 12 20]
 [11  7  1  1 20]]


b

In [53]:
# Create a 4x4 array and replace diagonal with 0
array_4x4 = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(array_4x4, 0)
print("4x4 Array with 0 Diagonal:")
print( array_4x4)


4x4 Array with 0 Diagonal:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


c

In [59]:
# Extract borders and corners from a 5x5 array
array_border = np.random.randint(0, 101, (5, 5))
print("Original Array:")
print(array_border)

borders = np.concatenate([array_border[0, :], array_border[-1, :], array_border[1:-1, 0], array_border[1:-1, -1]])
corners = array_border[np.ix_([0, -1], [0, -1])]
print("--------------------------------------------------------------------")
print("Borders:", borders)
print("--------------------------------------------------------------------")
print("Corners:")
print(corners)


Original Array:
[[68 36 31  8 98]
 [18 47 79  2 19]
 [23 53 32 23 74]
 [71 35 37 83 98]
 [88 98 24 92 17]]
--------------------------------------------------------------------
Borders: [68 36 31  8 98 88 98 24 92 17 18 23 71 19 74 98]
--------------------------------------------------------------------
Corners:
[[68 98]
 [88 17]]


d

In [61]:
# Normalize a 3x3 array
array_3x3 = np.arange(1, 10).reshape(3, 3)
mean = np.mean(array_3x3)
std = np.std(array_3x3)
normalized = (array_3x3 - mean) / std
print("Normalized 3x3 Array:")
print (normalized)

Normalized 3x3 Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


e

In [64]:
# e. Create a 4x4 array with random integers between 1 and 20
array_4x4 = np.random.randint(1, 21, (4, 4))

# Use Boolean indexing to set all elements greater than 10 to 10
array_4x4[array_4x4 > 10] = 10

# Print the modified array
print("Modified 4x4 Array (elements > 10 set to 10):")
print(array_4x4)

Modified 4x4 Array (elements > 10 set to 10):
[[10 10  4  3]
 [10 10 10 10]
 [ 6  3  9  5]
 [10 10  3  1]]


f

In [65]:
# Reverse a 1D array without using a function
array_1d = np.arange(1, 10)

# Print the original 1D array
print("Original 1D Array:")
print(array_1d)

# Reverse the array using slicing
reversed_array = array_1d[::-1]

# Print the reversed 1D array
print("Reversed 1D Array:")
print(reversed_array)

Original 1D Array:
[1 2 3 4 5 6 7 8 9]
Reversed 1D Array:
[9 8 7 6 5 4 3 2 1]


QUESTION 3: Monthly Temperature Analysis

a

In [68]:
# Store min and max monthly temperatures
temps_min = np.array([30.5, 38.4, 48.1, 56.8, 65.2, 75.9, 83.6, 86.5, 75.3, 64.6, 58.1, 45.4])
temps_max = np.array([48.2, 50.3, 58.7, 61.9, 70.5, 82.4, 88.2, 93.1, 86.7, 77.5, 67.2, 53.6])


b

In [69]:
# Statistics for min and max temperatures
temp_stats = {
    "Min Mean": np.mean(temps_min),
    "Max Mean": np.mean(temps_max),
    "Min Lowest": np.min(temps_min),
    "Max Highest": np.max(temps_max),
}
print(temp_stats)


{'Min Mean': 60.70000000000001, 'Max Mean': 69.85833333333335, 'Min Lowest': 30.5, 'Max Highest': 93.1}


c

In [72]:
# Compute average min and max temperatures for first and last quarters
first_quarter_avg = (np.mean(temps_min[:3]), np.mean(temps_max[:3]))
last_quarter_avg = (np.mean(temps_min[-3:]), np.mean(temps_max[-3:]))
print("First Quarter Avg (Jan - Mar):", first_quarter_avg)
print("Last Quarter Avg (Oct - Dec):", last_quarter_avg)


First Quarter Avg (Jan - Mar): (39.0, 52.4)
Last Quarter Avg (Oct - Dec): (56.03333333333333, 66.1)


d

In [74]:
# Calculate the average temperature of each month using both mean() and dot product operation

# Mean method
mthly_avg_mean = (temps_min + temps_max) / 2
print("Monthly Average Temperatures (using mean):", mthly_avg_mean)

# Dot product method (using the fact that the average of two numbers is their sum divided by 2)
weights = np.array([0.5, 0.5])  # Each temperature contributes equally to the average (i.e., 0.5 weight)
monthly_avg_dot_product = np.dot(np.vstack([temps_min, temps_max]).T, weights)  # Stack min and max and apply dot product
print("Monthly Average Temperatures (using dot product):", monthly_avg_dot_product)

#Compute monthly average using mean and dot product
weights = np.ones(12) / 12
monthly_avg = np.dot(weights, (temps_min + temps_max) / 2)
print("Monthly Average Temperatures:", monthly_avg)


Monthly Average Temperatures (using mean): [39.35 44.35 53.4  59.35 67.85 79.15 85.9  89.8  81.   71.05 62.65 49.5 ]
Monthly Average Temperatures (using dot product): [39.35 44.35 53.4  59.35 67.85 79.15 85.9  89.8  81.   71.05 62.65 49.5 ]
Monthly Average Temperatures: 65.27916666666667


e

QUESTION 4: Student Grades Analysis


In [83]:
np.random.seed(42)
grades = np.random.randint(60, 101, (20, 3))
print("Student Grades (Midterm 1, Midterm 2, Final Exam):\n")
print("(Midterm 1, Midterm 2, Final Exam):\n")
print(grades)

Student Grades (Midterm 1, Midterm 2, Final Exam):

(Midterm 1, Midterm 2, Final Exam):

[[98 88 74]
 [67 80 98]
 [78 82 70]
 [70 83 95]
 [99 83 62]
 [81 61 83]
 [89 97 61]
 [80 92 71]
 [81 84 86]
 [87 75 74]
 [62 96 66]
 [80 68 98]
 [77 63 84]
 [73 68 85]
 [61 79 87]
 [66 67 94]
 [73 76 95]
 [99 63 61]
 [65 63 88]
 [77 85 93]]


a

In [89]:
# Compute column-wise (test-wise) and row-wise (student-wise) averages
avg_per_exam = np.mean(grades, axis=0)  # Average for Midterm 1, Midterm 2, Final
avg_per_student = np.mean(grades, axis=1).reshape(-1, 1)   # Average per student

print("Average per Exam:", avg_per_exam)
print("--------------------------------------------------------------------")

print("Average per Student (Vertically):\n", avg_per_student)



Average per Exam: [78.15 77.65 81.25]
--------------------------------------------------------------------
Average per Student (Vertically):
 [[86.66666667]
 [81.66666667]
 [76.66666667]
 [82.66666667]
 [81.33333333]
 [75.        ]
 [82.33333333]
 [81.        ]
 [83.66666667]
 [78.66666667]
 [74.66666667]
 [82.        ]
 [74.66666667]
 [75.33333333]
 [75.66666667]
 [75.66666667]
 [81.33333333]
 [74.33333333]
 [72.        ]
 [85.        ]]


b

In [90]:
# Calculate max and min scores for each exam
max_scores = np.max(grades, axis=0)
min_scores = np.min(grades, axis=0)
print("Max Scores (Midterm 1, Midterm 2, Final):", max_scores)
print("Min Scores (Midterm 1, Midterm 2, Final):", min_scores)

Max Scores (Midterm 1, Midterm 2, Final): [99 97 98]
Min Scores (Midterm 1, Midterm 2, Final): [61 61 61]


c

In [91]:
# Calculate average grade for first two and last two students
avg_first_last_2= np.mean(grades[[0, 1, -2, -1]], axis=0)
print("Avg of first two and last two students:", avg_first_last_2)


Avg of first two and last two students: [76.75 79.   88.25]


d

In [92]:
# Compute the average of Midterm 1 and Midterm 2 grades for the first 10 students
avg_midterm_1_2_first_10 = np.mean(grades[:10, :2], axis=0)
print("Average of Midterm 1 and Midterm 2 for first 10 students:", avg_midterm_1_2_first_10)

Average of Midterm 1 and Midterm 2 for first 10 students: [83.  82.5]


e

In [93]:
# Students who scored >=75 in Midterm 2 or Final Exam
high_scorers = grades[(grades[:, 1] >= 75) | (grades[:, 2] >= 75)]
print("Students with >=75 in Midterm 2 or Final Exam:", high_scorers)

Students with >=75 in Midterm 2 or Final Exam: [[98 88 74]
 [67 80 98]
 [78 82 70]
 [70 83 95]
 [99 83 62]
 [81 61 83]
 [89 97 61]
 [80 92 71]
 [81 84 86]
 [87 75 74]
 [62 96 66]
 [80 68 98]
 [77 63 84]
 [73 68 85]
 [61 79 87]
 [66 67 94]
 [73 76 95]
 [65 63 88]
 [77 85 93]]


f

In [95]:
# Change scores <80 to 80, then compute alternate students' avg for Midterm 1 and Final
grades[grades < 80] = 80
alternate_avg = np.mean(grades[::2, [0, 2]], axis=0)
print("Alternate students' avg Midterm 1 & Final:", alternate_avg)

Alternate students' avg Midterm 1 & Final: [84.7 84. ]


g

In [98]:
# Calculate weighted total scores for first 10 students (30% Midterm 1, 30% Midterm 2, 40% Final)
weights = np.array([0.3, 0.3, 0.4])
total_scores = np.dot(grades[:10], weights).reshape(-1, 1)
print("Weighted total scores for first 10 students:\n", total_scores)


Weighted total scores for first 10 students:
 [[87.8]
 [87.2]
 [80.6]
 [86.9]
 [86.6]
 [81.5]
 [87.8]
 [83.6]
 [83.9]
 [82.1]]


h

In [100]:
# Increase Midterm 1 & 2 by 10%, decrease Final by 5%, converting the grades to integers
grades = grades.astype(float)  # Convert to float for percentage operations
grades[:, :2] *= 1.1  # Increase Midterm 1 & 2 by 10%
grades[:, 2] *= 0.95  # Decrease Final by 5%
grades = grades.astype(int)  # Convert back to integer
print("Updated Grades:\n", grades)


Updated Grades:
 [[117 105  72]
 [ 96  96  88]
 [ 96  99  72]
 [ 96 100  85]
 [118 100  72]
 [ 97  96  74]
 [106 116  72]
 [ 96 111  72]
 [ 97 101  76]
 [104  96  72]
 [ 96 115  72]
 [ 96  96  88]
 [ 96  96  75]
 [ 96  96  76]
 [ 96  96  77]
 [ 96  96  84]
 [ 96  96  85]
 [118  96  72]
 [ 96  96  78]
 [ 96 102  83]]


i

In [101]:
# Rescale test scores between 0 and 100 based on max score in each column
grades_scaled = (grades / np.max(grades, axis=0)) * 100
print("Rescaled Grades:\n", grades_scaled)

Rescaled Grades:
 [[ 99.15254237  90.51724138  81.81818182]
 [ 81.3559322   82.75862069 100.        ]
 [ 81.3559322   85.34482759  81.81818182]
 [ 81.3559322   86.20689655  96.59090909]
 [100.          86.20689655  81.81818182]
 [ 82.20338983  82.75862069  84.09090909]
 [ 89.83050847 100.          81.81818182]
 [ 81.3559322   95.68965517  81.81818182]
 [ 82.20338983  87.06896552  86.36363636]
 [ 88.13559322  82.75862069  81.81818182]
 [ 81.3559322   99.13793103  81.81818182]
 [ 81.3559322   82.75862069 100.        ]
 [ 81.3559322   82.75862069  85.22727273]
 [ 81.3559322   82.75862069  86.36363636]
 [ 81.3559322   82.75862069  87.5       ]
 [ 81.3559322   82.75862069  95.45454545]
 [ 81.3559322   82.75862069  96.59090909]
 [100.          82.75862069  81.81818182]
 [ 81.3559322   82.75862069  88.63636364]
 [ 81.3559322   87.93103448  94.31818182]]
